package com.bawei.liuqi20191209.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.liuqi20191209.bean.UriBean;

import com.bawei.liuqi20191209.dao.UriBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig uriBeanDaoConfig;

    private final UriBeanDao uriBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        uriBeanDaoConfig = daoConfigMap.get(UriBeanDao.class).clone();
        uriBeanDaoConfig.initIdentityScope(type);

        uriBeanDao = new UriBeanDao(uriBeanDaoConfig, this);

        registerDao(UriBean.class, uriBeanDao);
    }
    
    public void clear() {
        uriBeanDaoConfig.clearIdentityScope();
    }

    public UriBeanDao getUriBeanDao() {
        return uriBeanDao;
    }

}
